//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int alunoID { get; set; }
        public Nullable<int> nota { get; set; }
        public string curso { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string Nome { get; set; }
    }
}
